version: '3.8'
services:
  floodlight-controller:
    image: piyushk2001/floodlight-controller
    container_name: floodlight-controller
    # Expose Floodlight's web interface (8080) and OpenFlow channel (6653)
    ports:
      - "8080:8080"
      - "6653:6653"
    # Ensures the container restarts automatically if it exits
    restart: unless-stopped
